# Generated by Django 4.2 on 2026-04-16 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., 'Python Programming Tutoring'", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of what you offer, how long it takes, etc."
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tutoring", "Tutoring"),
                            ("tech", "Technology"),
                            ("creativity", "Creative Skills"),
                            ("sports", "Sports & Fitness"),
                            ("languages", "Languages"),
                            ("music", "Music"),
                            ("writing", "Writing"),
                            ("design", "Design"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("exchange", "Skill Exchange"),
                            ("paid", "Paid"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank if not paid",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("zoom", "Video Call (Zoom)"),
                            ("inperson", "In-Person"),
                            ("chat", "Chat/Messaging"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, help_text="Is this skill available right now?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "view_count",
                    models.IntegerField(default=0, help_text="Track popularity"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Tell other students about yourself",
                        null=True,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a profile picture",
                        null=True,
                        upload_to="profile_pics/",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="SkillRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(help_text="Why do you want this skill?")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("completed", "Completed"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, help_text="Responder's reply", null=True
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_requests_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="skillfeed.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "unique_together": {("requester", "skill")},
            },
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["owner", "-created_at"], name="skillfeed_s_owner_i_99680b_idx"
            ),
        ),
    ]
